// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capability/v1/capability.proto

package capabilityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateTextRequest 生成文本的请求
type GenerateTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"` // 可选，缺省走默认
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTextRequest) Reset() {
	*x = GenerateTextRequest{}
	mi := &file_capability_v1_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextRequest) ProtoMessage() {}

func (x *GenerateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capability_v1_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextRequest.ProtoReflect.Descriptor instead.
func (*GenerateTextRequest) Descriptor() ([]byte, []int) {
	return file_capability_v1_capability_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTextRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateTextRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateTextRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type GenerateTextResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Text             string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,3,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateTextResponse) Reset() {
	*x = GenerateTextResponse{}
	mi := &file_capability_v1_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextResponse) ProtoMessage() {}

func (x *GenerateTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capability_v1_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextResponse.ProtoReflect.Descriptor instead.
func (*GenerateTextResponse) Descriptor() ([]byte, []int) {
	return file_capability_v1_capability_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateTextResponse) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *GenerateTextResponse) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

// VectorizeTextRequest 文本向量化
type VectorizeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"` // collection name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeTextRequest) Reset() {
	*x = VectorizeTextRequest{}
	mi := &file_capability_v1_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeTextRequest) ProtoMessage() {}

func (x *VectorizeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capability_v1_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeTextRequest.ProtoReflect.Descriptor instead.
func (*VectorizeTextRequest) Descriptor() ([]byte, []int) {
	return file_capability_v1_capability_proto_rawDescGZIP(), []int{2}
}

func (x *VectorizeTextRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *VectorizeTextRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type VectorizeTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*Vector              `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	Dim           int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeTextResponse) Reset() {
	*x = VectorizeTextResponse{}
	mi := &file_capability_v1_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeTextResponse) ProtoMessage() {}

func (x *VectorizeTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capability_v1_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeTextResponse.ProtoReflect.Descriptor instead.
func (*VectorizeTextResponse) Descriptor() ([]byte, []int) {
	return file_capability_v1_capability_proto_rawDescGZIP(), []int{3}
}

func (x *VectorizeTextResponse) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *VectorizeTextResponse) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_capability_v1_capability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_capability_v1_capability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_capability_v1_capability_proto_rawDescGZIP(), []int{4}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_capability_v1_capability_proto protoreflect.FileDescriptor

const file_capability_v1_capability_proto_rawDesc = "" +
	"\n" +
	"\x1ecapability/v1/capability.proto\x12\rcapability.v1\"b\n" +
	"\x13GenerateTextRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\"|\n" +
	"\x14GenerateTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rprompt_tokens\x18\x02 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x03 \x01(\x05R\x10completionTokens\"L\n" +
	"\x14VectorizeTextRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"Z\n" +
	"\x15VectorizeTextResponse\x12/\n" +
	"\avectors\x18\x01 \x03(\v2\x15.capability.v1.VectorR\avectors\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\" \n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values2\xc8\x01\n" +
	"\x11CapabilityService\x12W\n" +
	"\fGenerateText\x12\".capability.v1.GenerateTextRequest\x1a#.capability.v1.GenerateTextResponse\x12Z\n" +
	"\rVectorizeText\x12#.capability.v1.VectorizeTextRequest\x1a$.capability.v1.VectorizeTextResponseB7Z5ai_system_oncall/api/proto/capability/v1;capabilityv1b\x06proto3"

var (
	file_capability_v1_capability_proto_rawDescOnce sync.Once
	file_capability_v1_capability_proto_rawDescData []byte
)

func file_capability_v1_capability_proto_rawDescGZIP() []byte {
	file_capability_v1_capability_proto_rawDescOnce.Do(func() {
		file_capability_v1_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capability_v1_capability_proto_rawDesc), len(file_capability_v1_capability_proto_rawDesc)))
	})
	return file_capability_v1_capability_proto_rawDescData
}

var file_capability_v1_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_capability_v1_capability_proto_goTypes = []any{
	(*GenerateTextRequest)(nil),   // 0: capability.v1.GenerateTextRequest
	(*GenerateTextResponse)(nil),  // 1: capability.v1.GenerateTextResponse
	(*VectorizeTextRequest)(nil),  // 2: capability.v1.VectorizeTextRequest
	(*VectorizeTextResponse)(nil), // 3: capability.v1.VectorizeTextResponse
	(*Vector)(nil),                // 4: capability.v1.Vector
}
var file_capability_v1_capability_proto_depIdxs = []int32{
	4, // 0: capability.v1.VectorizeTextResponse.vectors:type_name -> capability.v1.Vector
	0, // 1: capability.v1.CapabilityService.GenerateText:input_type -> capability.v1.GenerateTextRequest
	2, // 2: capability.v1.CapabilityService.VectorizeText:input_type -> capability.v1.VectorizeTextRequest
	1, // 3: capability.v1.CapabilityService.GenerateText:output_type -> capability.v1.GenerateTextResponse
	3, // 4: capability.v1.CapabilityService.VectorizeText:output_type -> capability.v1.VectorizeTextResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_capability_v1_capability_proto_init() }
func file_capability_v1_capability_proto_init() {
	if File_capability_v1_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capability_v1_capability_proto_rawDesc), len(file_capability_v1_capability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capability_v1_capability_proto_goTypes,
		DependencyIndexes: file_capability_v1_capability_proto_depIdxs,
		MessageInfos:      file_capability_v1_capability_proto_msgTypes,
	}.Build()
	File_capability_v1_capability_proto = out.File
	file_capability_v1_capability_proto_goTypes = nil
	file_capability_v1_capability_proto_depIdxs = nil
}
