// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: capability/v1/capability.proto

package capabilityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapabilityService_GenerateText_FullMethodName  = "/capability.v1.CapabilityService/GenerateText"
	CapabilityService_VectorizeText_FullMethodName = "/capability.v1.CapabilityService/VectorizeText"
)

// CapabilityServiceClient is the client API for CapabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapabilityService 暴露给 Go 后端调用的内部能力
type CapabilityServiceClient interface {
	// 部署在 Python Agent 上
	GenerateText(ctx context.Context, in *GenerateTextRequest, opts ...grpc.CallOption) (*GenerateTextResponse, error)
	// 部署在 Python RAG 模块上（或者由 Python Agent 转一道，简化起见同进程）
	VectorizeText(ctx context.Context, in *VectorizeTextRequest, opts ...grpc.CallOption) (*VectorizeTextResponse, error)
}

type capabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityServiceClient(cc grpc.ClientConnInterface) CapabilityServiceClient {
	return &capabilityServiceClient{cc}
}

func (c *capabilityServiceClient) GenerateText(ctx context.Context, in *GenerateTextRequest, opts ...grpc.CallOption) (*GenerateTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTextResponse)
	err := c.cc.Invoke(ctx, CapabilityService_GenerateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) VectorizeText(ctx context.Context, in *VectorizeTextRequest, opts ...grpc.CallOption) (*VectorizeTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorizeTextResponse)
	err := c.cc.Invoke(ctx, CapabilityService_VectorizeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilityServiceServer is the server API for CapabilityService service.
// All implementations must embed UnimplementedCapabilityServiceServer
// for forward compatibility.
//
// CapabilityService 暴露给 Go 后端调用的内部能力
type CapabilityServiceServer interface {
	// 部署在 Python Agent 上
	GenerateText(context.Context, *GenerateTextRequest) (*GenerateTextResponse, error)
	// 部署在 Python RAG 模块上（或者由 Python Agent 转一道，简化起见同进程）
	VectorizeText(context.Context, *VectorizeTextRequest) (*VectorizeTextResponse, error)
	mustEmbedUnimplementedCapabilityServiceServer()
}

// UnimplementedCapabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilityServiceServer struct{}

func (UnimplementedCapabilityServiceServer) GenerateText(context.Context, *GenerateTextRequest) (*GenerateTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateText not implemented")
}
func (UnimplementedCapabilityServiceServer) VectorizeText(context.Context, *VectorizeTextRequest) (*VectorizeTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorizeText not implemented")
}
func (UnimplementedCapabilityServiceServer) mustEmbedUnimplementedCapabilityServiceServer() {}
func (UnimplementedCapabilityServiceServer) testEmbeddedByValue()                           {}

// UnsafeCapabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityServiceServer will
// result in compilation errors.
type UnsafeCapabilityServiceServer interface {
	mustEmbedUnimplementedCapabilityServiceServer()
}

func RegisterCapabilityServiceServer(s grpc.ServiceRegistrar, srv CapabilityServiceServer) {
	// If the following call panics, it indicates UnimplementedCapabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilityService_ServiceDesc, srv)
}

func _CapabilityService_GenerateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).GenerateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_GenerateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).GenerateText(ctx, req.(*GenerateTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_VectorizeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorizeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).VectorizeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_VectorizeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).VectorizeText(ctx, req.(*VectorizeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapabilityService_ServiceDesc is the grpc.ServiceDesc for CapabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capability.v1.CapabilityService",
	HandlerType: (*CapabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateText",
			Handler:    _CapabilityService_GenerateText_Handler,
		},
		{
			MethodName: "VectorizeText",
			Handler:    _CapabilityService_VectorizeText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capability/v1/capability.proto",
}
