// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tooling/v1/tooling.proto

package toolingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 服务信息 ==========
type GetServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     uint64                 `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{0}
}

func (x *GetServiceRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

type GetServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type ListServicesByProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesByProjectRequest) Reset() {
	*x = ListServicesByProjectRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesByProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesByProjectRequest) ProtoMessage() {}

func (x *ListServicesByProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesByProjectRequest.ProtoReflect.Descriptor instead.
func (*ListServicesByProjectRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{2}
}

func (x *ListServicesByProjectRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type ListServicesByProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesByProjectResponse) Reset() {
	*x = ListServicesByProjectResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesByProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesByProjectResponse) ProtoMessage() {}

func (x *ListServicesByProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesByProjectResponse.ProtoReflect.Descriptor instead.
func (*ListServicesByProjectResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{3}
}

func (x *ListServicesByProjectResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     uint64                 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{4}
}

func (x *Service) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Service) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Service) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Service) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ========== 历史问题 ==========
type SearchHistoryIssuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	ProjectId     uint64                 `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // 0 = 全部
	IssueType     string                 `protobuf:"bytes,3,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHistoryIssuesRequest) Reset() {
	*x = SearchHistoryIssuesRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHistoryIssuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHistoryIssuesRequest) ProtoMessage() {}

func (x *SearchHistoryIssuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHistoryIssuesRequest.ProtoReflect.Descriptor instead.
func (*SearchHistoryIssuesRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{5}
}

func (x *SearchHistoryIssuesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchHistoryIssuesRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SearchHistoryIssuesRequest) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *SearchHistoryIssuesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchHistoryIssuesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchHistoryIssuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Issue               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHistoryIssuesResponse) Reset() {
	*x = SearchHistoryIssuesResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHistoryIssuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHistoryIssuesResponse) ProtoMessage() {}

func (x *SearchHistoryIssuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHistoryIssuesResponse.ProtoReflect.Descriptor instead.
func (*SearchHistoryIssuesResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{6}
}

func (x *SearchHistoryIssuesResponse) GetItems() []*Issue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchHistoryIssuesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IssueNo       string                 `protobuf:"bytes,2,opt,name=issue_no,json=issueNo,proto3" json:"issue_no,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	IssueType     string                 `protobuf:"bytes,6,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{7}
}

func (x *Issue) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Issue) GetIssueNo() string {
	if x != nil {
		return x.IssueNo
	}
	return ""
}

func (x *Issue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Issue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Issue) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Issue) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

// ========== 知识库 ==========
type SearchKnowledgeDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	DocType       string                 `protobuf:"bytes,2,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	ProjectId     uint64                 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchKnowledgeDocsRequest) Reset() {
	*x = SearchKnowledgeDocsRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKnowledgeDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKnowledgeDocsRequest) ProtoMessage() {}

func (x *SearchKnowledgeDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKnowledgeDocsRequest.ProtoReflect.Descriptor instead.
func (*SearchKnowledgeDocsRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{8}
}

func (x *SearchKnowledgeDocsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchKnowledgeDocsRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *SearchKnowledgeDocsRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SearchKnowledgeDocsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchKnowledgeDocsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchKnowledgeDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeDoc        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchKnowledgeDocsResponse) Reset() {
	*x = SearchKnowledgeDocsResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKnowledgeDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKnowledgeDocsResponse) ProtoMessage() {}

func (x *SearchKnowledgeDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKnowledgeDocsResponse.ProtoReflect.Descriptor instead.
func (*SearchKnowledgeDocsResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{9}
}

func (x *SearchKnowledgeDocsResponse) GetItems() []*KnowledgeDoc {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchKnowledgeDocsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetKnowledgeDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint64                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeDocRequest) Reset() {
	*x = GetKnowledgeDocRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeDocRequest) ProtoMessage() {}

func (x *GetKnowledgeDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeDocRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeDocRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{10}
}

func (x *GetKnowledgeDocRequest) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

type GetKnowledgeDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doc           *KnowledgeDoc          `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeDocResponse) Reset() {
	*x = GetKnowledgeDocResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeDocResponse) ProtoMessage() {}

func (x *GetKnowledgeDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeDocResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeDocResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{11}
}

func (x *GetKnowledgeDocResponse) GetDoc() *KnowledgeDoc {
	if x != nil {
		return x.Doc
	}
	return nil
}

type KnowledgeDoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DocType       string                 `protobuf:"bytes,3,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeDoc) Reset() {
	*x = KnowledgeDoc{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeDoc) ProtoMessage() {}

func (x *KnowledgeDoc) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeDoc.ProtoReflect.Descriptor instead.
func (*KnowledgeDoc) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{12}
}

func (x *KnowledgeDoc) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KnowledgeDoc) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeDoc) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *KnowledgeDoc) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ========== 日志 ==========
type GetLogsByTraceIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsByTraceIDRequest) Reset() {
	*x = GetLogsByTraceIDRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsByTraceIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsByTraceIDRequest) ProtoMessage() {}

func (x *GetLogsByTraceIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsByTraceIDRequest.ProtoReflect.Descriptor instead.
func (*GetLogsByTraceIDRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{13}
}

func (x *GetLogsByTraceIDRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetLogsByTraceIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsByTraceIDResponse) Reset() {
	*x = GetLogsByTraceIDResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsByTraceIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsByTraceIDResponse) ProtoMessage() {}

func (x *GetLogsByTraceIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsByTraceIDResponse.ProtoReflect.Descriptor instead.
func (*GetLogsByTraceIDResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{14}
}

func (x *GetLogsByTraceIDResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetServiceLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     uint64                 `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceLogsRequest) Reset() {
	*x = GetServiceLogsRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceLogsRequest) ProtoMessage() {}

func (x *GetServiceLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceLogsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceLogsRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{15}
}

func (x *GetServiceLogsRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *GetServiceLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetServiceLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceLogsResponse) Reset() {
	*x = GetServiceLogsResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceLogsResponse) ProtoMessage() {}

func (x *GetServiceLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceLogsResponse.ProtoReflect.Descriptor instead.
func (*GetServiceLogsResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{16}
}

func (x *GetServiceLogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SearchLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // 0 = 全部
	ServiceId     uint64                 `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // 0 = 全部
	LogLevel      string                 `protobuf:"bytes,3,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`     // INFO/WARN/ERROR
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsRequest) Reset() {
	*x = SearchLogsRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsRequest) ProtoMessage() {}

func (x *SearchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsRequest.ProtoReflect.Descriptor instead.
func (*SearchLogsRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{17}
}

func (x *SearchLogsRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SearchLogsRequest) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *SearchLogsRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *SearchLogsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsResponse) Reset() {
	*x = SearchLogsResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsResponse) ProtoMessage() {}

func (x *SearchLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsResponse.ProtoReflect.Descriptor instead.
func (*SearchLogsResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{18}
}

func (x *SearchLogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{19}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// ========== 问题更新 ==========
type UpdateIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssueId       uint64                 `protobuf:"varint,1,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 简化为 string→string，由 Go 端做类型转换
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueRequest) Reset() {
	*x = UpdateIssueRequest{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueRequest) ProtoMessage() {}

func (x *UpdateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueRequest) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateIssueRequest) GetIssueId() uint64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *UpdateIssueRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type UpdateIssueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issue         *Issue                 `protobuf:"bytes,1,opt,name=issue,proto3" json:"issue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIssueResponse) Reset() {
	*x = UpdateIssueResponse{}
	mi := &file_tooling_v1_tooling_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueResponse) ProtoMessage() {}

func (x *UpdateIssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tooling_v1_tooling_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueResponse.ProtoReflect.Descriptor instead.
func (*UpdateIssueResponse) Descriptor() ([]byte, []int) {
	return file_tooling_v1_tooling_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateIssueResponse) GetIssue() *Issue {
	if x != nil {
		return x.Issue
	}
	return nil
}

var File_tooling_v1_tooling_proto protoreflect.FileDescriptor

const file_tooling_v1_tooling_proto_rawDesc = "" +
	"\n" +
	"\x18tooling/v1/tooling.proto\x12\n" +
	"tooling.v1\"2\n" +
	"\x11GetServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x04R\tserviceId\"C\n" +
	"\x12GetServiceResponse\x12-\n" +
	"\aservice\x18\x01 \x01(\v2\x13.tooling.v1.ServiceR\aservice\"=\n" +
	"\x1cListServicesByProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\"P\n" +
	"\x1dListServicesByProjectResponse\x12/\n" +
	"\bservices\x18\x01 \x03(\v2\x13.tooling.v1.ServiceR\bservices\"\x96\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x04R\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\xa5\x01\n" +
	"\x1aSearchHistoryIssuesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x04R\tprojectId\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x03 \x01(\tR\tissueType\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\\\n" +
	"\x1bSearchHistoryIssuesResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.tooling.v1.IssueR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x9b\x01\n" +
	"\x05Issue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bissue_no\x18\x02 \x01(\tR\aissueNo\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x06 \x01(\tR\tissueType\"\xa1\x01\n" +
	"\x1aSearchKnowledgeDocsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x19\n" +
	"\bdoc_type\x18\x02 \x01(\tR\adocType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x04R\tprojectId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"c\n" +
	"\x1bSearchKnowledgeDocsResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.tooling.v1.KnowledgeDocR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"/\n" +
	"\x16GetKnowledgeDocRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x04R\x05docId\"E\n" +
	"\x17GetKnowledgeDocResponse\x12*\n" +
	"\x03doc\x18\x01 \x01(\v2\x18.tooling.v1.KnowledgeDocR\x03doc\"i\n" +
	"\fKnowledgeDoc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bdoc_type\x18\x03 \x01(\tR\adocType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"4\n" +
	"\x17GetLogsByTraceIDRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"J\n" +
	"\x18GetLogsByTraceIDResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.tooling.v1.LogEntryR\aentries\"L\n" +
	"\x15GetServiceLogsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x04R\tserviceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"H\n" +
	"\x16GetServiceLogsResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.tooling.v1.LogEntryR\aentries\"\x9e\x01\n" +
	"\x11SearchLogsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x04R\tserviceId\x12\x1b\n" +
	"\tlog_level\x18\x03 \x01(\tR\blogLevel\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"D\n" +
	"\x12SearchLogsResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.tooling.v1.LogEntryR\aentries\"\x8d\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"\xae\x01\n" +
	"\x12UpdateIssueRequest\x12\x19\n" +
	"\bissue_id\x18\x01 \x01(\x04R\aissueId\x12B\n" +
	"\x06fields\x18\x02 \x03(\v2*.tooling.v1.UpdateIssueRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x13UpdateIssueResponse\x12'\n" +
	"\x05issue\x18\x01 \x01(\v2\x11.tooling.v1.IssueR\x05issue2\xcc\x06\n" +
	"\x0eToolingService\x12K\n" +
	"\n" +
	"GetService\x12\x1d.tooling.v1.GetServiceRequest\x1a\x1e.tooling.v1.GetServiceResponse\x12l\n" +
	"\x15ListServicesByProject\x12(.tooling.v1.ListServicesByProjectRequest\x1a).tooling.v1.ListServicesByProjectResponse\x12f\n" +
	"\x13SearchHistoryIssues\x12&.tooling.v1.SearchHistoryIssuesRequest\x1a'.tooling.v1.SearchHistoryIssuesResponse\x12f\n" +
	"\x13SearchKnowledgeDocs\x12&.tooling.v1.SearchKnowledgeDocsRequest\x1a'.tooling.v1.SearchKnowledgeDocsResponse\x12Z\n" +
	"\x0fGetKnowledgeDoc\x12\".tooling.v1.GetKnowledgeDocRequest\x1a#.tooling.v1.GetKnowledgeDocResponse\x12]\n" +
	"\x10GetLogsByTraceID\x12#.tooling.v1.GetLogsByTraceIDRequest\x1a$.tooling.v1.GetLogsByTraceIDResponse\x12W\n" +
	"\x0eGetServiceLogs\x12!.tooling.v1.GetServiceLogsRequest\x1a\".tooling.v1.GetServiceLogsResponse\x12K\n" +
	"\n" +
	"SearchLogs\x12\x1d.tooling.v1.SearchLogsRequest\x1a\x1e.tooling.v1.SearchLogsResponse\x12N\n" +
	"\vUpdateIssue\x12\x1e.tooling.v1.UpdateIssueRequest\x1a\x1f.tooling.v1.UpdateIssueResponseB1Z/ai_system_oncall/api/proto/tooling/v1;toolingv1b\x06proto3"

var (
	file_tooling_v1_tooling_proto_rawDescOnce sync.Once
	file_tooling_v1_tooling_proto_rawDescData []byte
)

func file_tooling_v1_tooling_proto_rawDescGZIP() []byte {
	file_tooling_v1_tooling_proto_rawDescOnce.Do(func() {
		file_tooling_v1_tooling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tooling_v1_tooling_proto_rawDesc), len(file_tooling_v1_tooling_proto_rawDesc)))
	})
	return file_tooling_v1_tooling_proto_rawDescData
}

var file_tooling_v1_tooling_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_tooling_v1_tooling_proto_goTypes = []any{
	(*GetServiceRequest)(nil),             // 0: tooling.v1.GetServiceRequest
	(*GetServiceResponse)(nil),            // 1: tooling.v1.GetServiceResponse
	(*ListServicesByProjectRequest)(nil),  // 2: tooling.v1.ListServicesByProjectRequest
	(*ListServicesByProjectResponse)(nil), // 3: tooling.v1.ListServicesByProjectResponse
	(*Service)(nil),                       // 4: tooling.v1.Service
	(*SearchHistoryIssuesRequest)(nil),    // 5: tooling.v1.SearchHistoryIssuesRequest
	(*SearchHistoryIssuesResponse)(nil),   // 6: tooling.v1.SearchHistoryIssuesResponse
	(*Issue)(nil),                         // 7: tooling.v1.Issue
	(*SearchKnowledgeDocsRequest)(nil),    // 8: tooling.v1.SearchKnowledgeDocsRequest
	(*SearchKnowledgeDocsResponse)(nil),   // 9: tooling.v1.SearchKnowledgeDocsResponse
	(*GetKnowledgeDocRequest)(nil),        // 10: tooling.v1.GetKnowledgeDocRequest
	(*GetKnowledgeDocResponse)(nil),       // 11: tooling.v1.GetKnowledgeDocResponse
	(*KnowledgeDoc)(nil),                  // 12: tooling.v1.KnowledgeDoc
	(*GetLogsByTraceIDRequest)(nil),       // 13: tooling.v1.GetLogsByTraceIDRequest
	(*GetLogsByTraceIDResponse)(nil),      // 14: tooling.v1.GetLogsByTraceIDResponse
	(*GetServiceLogsRequest)(nil),         // 15: tooling.v1.GetServiceLogsRequest
	(*GetServiceLogsResponse)(nil),        // 16: tooling.v1.GetServiceLogsResponse
	(*SearchLogsRequest)(nil),             // 17: tooling.v1.SearchLogsRequest
	(*SearchLogsResponse)(nil),            // 18: tooling.v1.SearchLogsResponse
	(*LogEntry)(nil),                      // 19: tooling.v1.LogEntry
	(*UpdateIssueRequest)(nil),            // 20: tooling.v1.UpdateIssueRequest
	(*UpdateIssueResponse)(nil),           // 21: tooling.v1.UpdateIssueResponse
	nil,                                   // 22: tooling.v1.UpdateIssueRequest.FieldsEntry
}
var file_tooling_v1_tooling_proto_depIdxs = []int32{
	4,  // 0: tooling.v1.GetServiceResponse.service:type_name -> tooling.v1.Service
	4,  // 1: tooling.v1.ListServicesByProjectResponse.services:type_name -> tooling.v1.Service
	7,  // 2: tooling.v1.SearchHistoryIssuesResponse.items:type_name -> tooling.v1.Issue
	12, // 3: tooling.v1.SearchKnowledgeDocsResponse.items:type_name -> tooling.v1.KnowledgeDoc
	12, // 4: tooling.v1.GetKnowledgeDocResponse.doc:type_name -> tooling.v1.KnowledgeDoc
	19, // 5: tooling.v1.GetLogsByTraceIDResponse.entries:type_name -> tooling.v1.LogEntry
	19, // 6: tooling.v1.GetServiceLogsResponse.entries:type_name -> tooling.v1.LogEntry
	19, // 7: tooling.v1.SearchLogsResponse.entries:type_name -> tooling.v1.LogEntry
	22, // 8: tooling.v1.UpdateIssueRequest.fields:type_name -> tooling.v1.UpdateIssueRequest.FieldsEntry
	7,  // 9: tooling.v1.UpdateIssueResponse.issue:type_name -> tooling.v1.Issue
	0,  // 10: tooling.v1.ToolingService.GetService:input_type -> tooling.v1.GetServiceRequest
	2,  // 11: tooling.v1.ToolingService.ListServicesByProject:input_type -> tooling.v1.ListServicesByProjectRequest
	5,  // 12: tooling.v1.ToolingService.SearchHistoryIssues:input_type -> tooling.v1.SearchHistoryIssuesRequest
	8,  // 13: tooling.v1.ToolingService.SearchKnowledgeDocs:input_type -> tooling.v1.SearchKnowledgeDocsRequest
	10, // 14: tooling.v1.ToolingService.GetKnowledgeDoc:input_type -> tooling.v1.GetKnowledgeDocRequest
	13, // 15: tooling.v1.ToolingService.GetLogsByTraceID:input_type -> tooling.v1.GetLogsByTraceIDRequest
	15, // 16: tooling.v1.ToolingService.GetServiceLogs:input_type -> tooling.v1.GetServiceLogsRequest
	17, // 17: tooling.v1.ToolingService.SearchLogs:input_type -> tooling.v1.SearchLogsRequest
	20, // 18: tooling.v1.ToolingService.UpdateIssue:input_type -> tooling.v1.UpdateIssueRequest
	1,  // 19: tooling.v1.ToolingService.GetService:output_type -> tooling.v1.GetServiceResponse
	3,  // 20: tooling.v1.ToolingService.ListServicesByProject:output_type -> tooling.v1.ListServicesByProjectResponse
	6,  // 21: tooling.v1.ToolingService.SearchHistoryIssues:output_type -> tooling.v1.SearchHistoryIssuesResponse
	9,  // 22: tooling.v1.ToolingService.SearchKnowledgeDocs:output_type -> tooling.v1.SearchKnowledgeDocsResponse
	11, // 23: tooling.v1.ToolingService.GetKnowledgeDoc:output_type -> tooling.v1.GetKnowledgeDocResponse
	14, // 24: tooling.v1.ToolingService.GetLogsByTraceID:output_type -> tooling.v1.GetLogsByTraceIDResponse
	16, // 25: tooling.v1.ToolingService.GetServiceLogs:output_type -> tooling.v1.GetServiceLogsResponse
	18, // 26: tooling.v1.ToolingService.SearchLogs:output_type -> tooling.v1.SearchLogsResponse
	21, // 27: tooling.v1.ToolingService.UpdateIssue:output_type -> tooling.v1.UpdateIssueResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_tooling_v1_tooling_proto_init() }
func file_tooling_v1_tooling_proto_init() {
	if File_tooling_v1_tooling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tooling_v1_tooling_proto_rawDesc), len(file_tooling_v1_tooling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tooling_v1_tooling_proto_goTypes,
		DependencyIndexes: file_tooling_v1_tooling_proto_depIdxs,
		MessageInfos:      file_tooling_v1_tooling_proto_msgTypes,
	}.Build()
	File_tooling_v1_tooling_proto = out.File
	file_tooling_v1_tooling_proto_goTypes = nil
	file_tooling_v1_tooling_proto_depIdxs = nil
}
