// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: tooling/v1/tooling.proto

package toolingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolingService_GetService_FullMethodName            = "/tooling.v1.ToolingService/GetService"
	ToolingService_ListServicesByProject_FullMethodName = "/tooling.v1.ToolingService/ListServicesByProject"
	ToolingService_SearchHistoryIssues_FullMethodName   = "/tooling.v1.ToolingService/SearchHistoryIssues"
	ToolingService_SearchKnowledgeDocs_FullMethodName   = "/tooling.v1.ToolingService/SearchKnowledgeDocs"
	ToolingService_GetKnowledgeDoc_FullMethodName       = "/tooling.v1.ToolingService/GetKnowledgeDoc"
	ToolingService_GetLogsByTraceID_FullMethodName      = "/tooling.v1.ToolingService/GetLogsByTraceID"
	ToolingService_GetServiceLogs_FullMethodName        = "/tooling.v1.ToolingService/GetServiceLogs"
	ToolingService_SearchLogs_FullMethodName            = "/tooling.v1.ToolingService/SearchLogs"
	ToolingService_UpdateIssue_FullMethodName           = "/tooling.v1.ToolingService/UpdateIssue"
)

// ToolingServiceClient is the client API for ToolingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ToolingService 挂在 Go 后端的内部窄面
type ToolingServiceClient interface {
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error)
	ListServicesByProject(ctx context.Context, in *ListServicesByProjectRequest, opts ...grpc.CallOption) (*ListServicesByProjectResponse, error)
	SearchHistoryIssues(ctx context.Context, in *SearchHistoryIssuesRequest, opts ...grpc.CallOption) (*SearchHistoryIssuesResponse, error)
	SearchKnowledgeDocs(ctx context.Context, in *SearchKnowledgeDocsRequest, opts ...grpc.CallOption) (*SearchKnowledgeDocsResponse, error)
	GetKnowledgeDoc(ctx context.Context, in *GetKnowledgeDocRequest, opts ...grpc.CallOption) (*GetKnowledgeDocResponse, error)
	GetLogsByTraceID(ctx context.Context, in *GetLogsByTraceIDRequest, opts ...grpc.CallOption) (*GetLogsByTraceIDResponse, error)
	GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (*GetServiceLogsResponse, error)
	SearchLogs(ctx context.Context, in *SearchLogsRequest, opts ...grpc.CallOption) (*SearchLogsResponse, error)
	UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*UpdateIssueResponse, error)
}

type toolingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolingServiceClient(cc grpc.ClientConnInterface) ToolingServiceClient {
	return &toolingServiceClient{cc}
}

func (c *toolingServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceResponse)
	err := c.cc.Invoke(ctx, ToolingService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingServiceClient) ListServicesByProject(ctx context.Context, in *ListServicesByProjectRequest, opts ...grpc.CallOption) (*ListServicesByProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesByProjectResponse)
	err := c.cc.Invoke(ctx, ToolingService_ListServicesByProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingServiceClient) SearchHistoryIssues(ctx context.Context, in *SearchHistoryIssuesRequest, opts ...grpc.CallOption) (*SearchHistoryIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchHistoryIssuesResponse)
	err := c.cc.Invoke(ctx, ToolingService_SearchHistoryIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingServiceClient) SearchKnowledgeDocs(ctx context.Context, in *SearchKnowledgeDocsRequest, opts ...grpc.CallOption) (*SearchKnowledgeDocsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKnowledgeDocsResponse)
	err := c.cc.Invoke(ctx, ToolingService_SearchKnowledgeDocs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingServiceClient) GetKnowledgeDoc(ctx context.Context, in *GetKnowledgeDocRequest, opts ...grpc.CallOption) (*GetKnowledgeDocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKnowledgeDocResponse)
	err := c.cc.Invoke(ctx, ToolingService_GetKnowledgeDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingServiceClient) GetLogsByTraceID(ctx context.Context, in *GetLogsByTraceIDRequest, opts ...grpc.CallOption) (*GetLogsByTraceIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogsByTraceIDResponse)
	err := c.cc.Invoke(ctx, ToolingService_GetLogsByTraceID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingServiceClient) GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (*GetServiceLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceLogsResponse)
	err := c.cc.Invoke(ctx, ToolingService_GetServiceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingServiceClient) SearchLogs(ctx context.Context, in *SearchLogsRequest, opts ...grpc.CallOption) (*SearchLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchLogsResponse)
	err := c.cc.Invoke(ctx, ToolingService_SearchLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolingServiceClient) UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*UpdateIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIssueResponse)
	err := c.cc.Invoke(ctx, ToolingService_UpdateIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolingServiceServer is the server API for ToolingService service.
// All implementations must embed UnimplementedToolingServiceServer
// for forward compatibility.
//
// ToolingService 挂在 Go 后端的内部窄面
type ToolingServiceServer interface {
	GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error)
	ListServicesByProject(context.Context, *ListServicesByProjectRequest) (*ListServicesByProjectResponse, error)
	SearchHistoryIssues(context.Context, *SearchHistoryIssuesRequest) (*SearchHistoryIssuesResponse, error)
	SearchKnowledgeDocs(context.Context, *SearchKnowledgeDocsRequest) (*SearchKnowledgeDocsResponse, error)
	GetKnowledgeDoc(context.Context, *GetKnowledgeDocRequest) (*GetKnowledgeDocResponse, error)
	GetLogsByTraceID(context.Context, *GetLogsByTraceIDRequest) (*GetLogsByTraceIDResponse, error)
	GetServiceLogs(context.Context, *GetServiceLogsRequest) (*GetServiceLogsResponse, error)
	SearchLogs(context.Context, *SearchLogsRequest) (*SearchLogsResponse, error)
	UpdateIssue(context.Context, *UpdateIssueRequest) (*UpdateIssueResponse, error)
	mustEmbedUnimplementedToolingServiceServer()
}

// UnimplementedToolingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolingServiceServer struct{}

func (UnimplementedToolingServiceServer) GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedToolingServiceServer) ListServicesByProject(context.Context, *ListServicesByProjectRequest) (*ListServicesByProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServicesByProject not implemented")
}
func (UnimplementedToolingServiceServer) SearchHistoryIssues(context.Context, *SearchHistoryIssuesRequest) (*SearchHistoryIssuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchHistoryIssues not implemented")
}
func (UnimplementedToolingServiceServer) SearchKnowledgeDocs(context.Context, *SearchKnowledgeDocsRequest) (*SearchKnowledgeDocsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchKnowledgeDocs not implemented")
}
func (UnimplementedToolingServiceServer) GetKnowledgeDoc(context.Context, *GetKnowledgeDocRequest) (*GetKnowledgeDocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKnowledgeDoc not implemented")
}
func (UnimplementedToolingServiceServer) GetLogsByTraceID(context.Context, *GetLogsByTraceIDRequest) (*GetLogsByTraceIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogsByTraceID not implemented")
}
func (UnimplementedToolingServiceServer) GetServiceLogs(context.Context, *GetServiceLogsRequest) (*GetServiceLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceLogs not implemented")
}
func (UnimplementedToolingServiceServer) SearchLogs(context.Context, *SearchLogsRequest) (*SearchLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchLogs not implemented")
}
func (UnimplementedToolingServiceServer) UpdateIssue(context.Context, *UpdateIssueRequest) (*UpdateIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateIssue not implemented")
}
func (UnimplementedToolingServiceServer) mustEmbedUnimplementedToolingServiceServer() {}
func (UnimplementedToolingServiceServer) testEmbeddedByValue()                        {}

// UnsafeToolingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolingServiceServer will
// result in compilation errors.
type UnsafeToolingServiceServer interface {
	mustEmbedUnimplementedToolingServiceServer()
}

func RegisterToolingServiceServer(s grpc.ServiceRegistrar, srv ToolingServiceServer) {
	// If the following call panics, it indicates UnimplementedToolingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolingService_ServiceDesc, srv)
}

func _ToolingService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolingService_ListServicesByProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesByProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).ListServicesByProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_ListServicesByProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).ListServicesByProject(ctx, req.(*ListServicesByProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolingService_SearchHistoryIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHistoryIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).SearchHistoryIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_SearchHistoryIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).SearchHistoryIssues(ctx, req.(*SearchHistoryIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolingService_SearchKnowledgeDocs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKnowledgeDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).SearchKnowledgeDocs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_SearchKnowledgeDocs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).SearchKnowledgeDocs(ctx, req.(*SearchKnowledgeDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolingService_GetKnowledgeDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgeDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).GetKnowledgeDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_GetKnowledgeDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).GetKnowledgeDoc(ctx, req.(*GetKnowledgeDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolingService_GetLogsByTraceID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsByTraceIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).GetLogsByTraceID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_GetLogsByTraceID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).GetLogsByTraceID(ctx, req.(*GetLogsByTraceIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolingService_GetServiceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).GetServiceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_GetServiceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).GetServiceLogs(ctx, req.(*GetServiceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolingService_SearchLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).SearchLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_SearchLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).SearchLogs(ctx, req.(*SearchLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolingService_UpdateIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolingServiceServer).UpdateIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolingService_UpdateIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolingServiceServer).UpdateIssue(ctx, req.(*UpdateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolingService_ServiceDesc is the grpc.ServiceDesc for ToolingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tooling.v1.ToolingService",
	HandlerType: (*ToolingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetService",
			Handler:    _ToolingService_GetService_Handler,
		},
		{
			MethodName: "ListServicesByProject",
			Handler:    _ToolingService_ListServicesByProject_Handler,
		},
		{
			MethodName: "SearchHistoryIssues",
			Handler:    _ToolingService_SearchHistoryIssues_Handler,
		},
		{
			MethodName: "SearchKnowledgeDocs",
			Handler:    _ToolingService_SearchKnowledgeDocs_Handler,
		},
		{
			MethodName: "GetKnowledgeDoc",
			Handler:    _ToolingService_GetKnowledgeDoc_Handler,
		},
		{
			MethodName: "GetLogsByTraceID",
			Handler:    _ToolingService_GetLogsByTraceID_Handler,
		},
		{
			MethodName: "GetServiceLogs",
			Handler:    _ToolingService_GetServiceLogs_Handler,
		},
		{
			MethodName: "SearchLogs",
			Handler:    _ToolingService_SearchLogs_Handler,
		},
		{
			MethodName: "UpdateIssue",
			Handler:    _ToolingService_UpdateIssue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tooling/v1/tooling.proto",
}
