// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rag/v1/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 文本向量化 ==========
// 直接传纯文本（已由调用方解析好），rag-engine 负责切分+embedding+存储
type VectorizeTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint64                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DocType       string                 `protobuf:"bytes,3,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	ProjectName   string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	HeadingPath   string                 `protobuf:"bytes,6,opt,name=heading_path,json=headingPath,proto3" json:"heading_path,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeTextRequest) Reset() {
	*x = VectorizeTextRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeTextRequest) ProtoMessage() {}

func (x *VectorizeTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeTextRequest.ProtoReflect.Descriptor instead.
func (*VectorizeTextRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *VectorizeTextRequest) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *VectorizeTextRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VectorizeTextRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *VectorizeTextRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *VectorizeTextRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *VectorizeTextRequest) GetHeadingPath() string {
	if x != nil {
		return x.HeadingPath
	}
	return ""
}

func (x *VectorizeTextRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type VectorizeTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoredChunks  int32                  `protobuf:"varint,1,opt,name=stored_chunks,json=storedChunks,proto3" json:"stored_chunks,omitempty"`
	DeletedChunks int32                  `protobuf:"varint,2,opt,name=deleted_chunks,json=deletedChunks,proto3" json:"deleted_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeTextResponse) Reset() {
	*x = VectorizeTextResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeTextResponse) ProtoMessage() {}

func (x *VectorizeTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeTextResponse.ProtoReflect.Descriptor instead.
func (*VectorizeTextResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *VectorizeTextResponse) GetStoredChunks() int32 {
	if x != nil {
		return x.StoredChunks
	}
	return 0
}

func (x *VectorizeTextResponse) GetDeletedChunks() int32 {
	if x != nil {
		return x.DeletedChunks
	}
	return 0
}

// ========== 文档向量化（带文件解析） ==========
// 文件由 rag-engine 解析（md/docx/pdf），调用方只传原始字节
type VectorizeDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint64                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DocType       string                 `protobuf:"bytes,3,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`
	ProjectName   string                 `protobuf:"bytes,4,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Filename      string                 `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"` // 决定解析器：md/docx/pdf
	Content       []byte                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeDocumentRequest) Reset() {
	*x = VectorizeDocumentRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeDocumentRequest) ProtoMessage() {}

func (x *VectorizeDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeDocumentRequest.ProtoReflect.Descriptor instead.
func (*VectorizeDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *VectorizeDocumentRequest) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *VectorizeDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *VectorizeDocumentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type VectorizeDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoredChunks  int32                  `protobuf:"varint,1,opt,name=stored_chunks,json=storedChunks,proto3" json:"stored_chunks,omitempty"`
	DeletedChunks int32                  `protobuf:"varint,2,opt,name=deleted_chunks,json=deletedChunks,proto3" json:"deleted_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorizeDocumentResponse) Reset() {
	*x = VectorizeDocumentResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorizeDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorizeDocumentResponse) ProtoMessage() {}

func (x *VectorizeDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorizeDocumentResponse.ProtoReflect.Descriptor instead.
func (*VectorizeDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *VectorizeDocumentResponse) GetStoredChunks() int32 {
	if x != nil {
		return x.StoredChunks
	}
	return 0
}

func (x *VectorizeDocumentResponse) GetDeletedChunks() int32 {
	if x != nil {
		return x.DeletedChunks
	}
	return 0
}

// ========== 删除 ==========
type DeleteByDocIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint64                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByDocIdRequest) Reset() {
	*x = DeleteByDocIdRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByDocIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByDocIdRequest) ProtoMessage() {}

func (x *DeleteByDocIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByDocIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteByDocIdRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteByDocIdRequest) GetDocId() uint64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

type DeleteByDocIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedChunks int32                  `protobuf:"varint,1,opt,name=deleted_chunks,json=deletedChunks,proto3" json:"deleted_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByDocIdResponse) Reset() {
	*x = DeleteByDocIdResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByDocIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByDocIdResponse) ProtoMessage() {}

func (x *DeleteByDocIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByDocIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteByDocIdResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteByDocIdResponse) GetDeletedChunks() int32 {
	if x != nil {
		return x.DeletedChunks
	}
	return 0
}

// ========== 检索 ==========
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"` // 过滤
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // 过滤
	DocType       string                 `protobuf:"bytes,5,opt,name=doc_type,json=docType,proto3" json:"doc_type,omitempty"`             // 过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *SearchRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SearchRequest) GetDocType() string {
	if x != nil {
		return x.DocType
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // doc_id / title / heading_path 等
	Distance      float64                `protobuf:"fixed64,4,opt,name=distance,proto3" json:"distance,omitempty"`
	Similarity    float64                `protobuf:"fixed64,5,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_rag_v1_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{8}
}

func (x *SearchHit) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SearchHit) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchHit) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchHit) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchHit) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

// ========== 统计 ==========
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{9}
}

type GetStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalChunks    int64                  `protobuf:"varint,1,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	CollectionName string                 `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	EmbeddingModel string                 `protobuf:"bytes,3,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatsResponse) GetTotalChunks() int64 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *GetStatsResponse) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *GetStatsResponse) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

var File_rag_v1_rag_proto protoreflect.FileDescriptor

const file_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10rag/v1/rag.proto\x12\x06rag.v1\"\xe1\x01\n" +
	"\x14VectorizeTextRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x04R\x05docId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bdoc_type\x18\x03 \x01(\tR\adocType\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12!\n" +
	"\fheading_path\x18\x06 \x01(\tR\vheadingPath\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\"c\n" +
	"\x15VectorizeTextResponse\x12#\n" +
	"\rstored_chunks\x18\x01 \x01(\x05R\fstoredChunks\x12%\n" +
	"\x0edeleted_chunks\x18\x02 \x01(\x05R\rdeletedChunks\"\xde\x01\n" +
	"\x18VectorizeDocumentRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x04R\x05docId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bdoc_type\x18\x03 \x01(\tR\adocType\x12!\n" +
	"\fproject_name\x18\x04 \x01(\tR\vprojectName\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bfilename\x18\x06 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\a \x01(\fR\acontent\"g\n" +
	"\x19VectorizeDocumentResponse\x12#\n" +
	"\rstored_chunks\x18\x01 \x01(\x05R\fstoredChunks\x12%\n" +
	"\x0edeleted_chunks\x18\x02 \x01(\x05R\rdeletedChunks\"-\n" +
	"\x14DeleteByDocIdRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\x04R\x05docId\">\n" +
	"\x15DeleteByDocIdResponse\x12%\n" +
	"\x0edeleted_chunks\x18\x01 \x01(\x05R\rdeletedChunks\"\x9b\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12\x19\n" +
	"\bdoc_type\x18\x05 \x01(\tR\adocType\"7\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x04hits\x18\x01 \x03(\v2\x11.rag.v1.SearchHitR\x04hits\"\xf6\x01\n" +
	"\tSearchHit\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12;\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1f.rag.v1.SearchHit.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x01R\bdistance\x12\x1e\n" +
	"\n" +
	"similarity\x18\x05 \x01(\x01R\n" +
	"similarity\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fGetStatsRequest\"\x87\x01\n" +
	"\x10GetStatsResponse\x12!\n" +
	"\ftotal_chunks\x18\x01 \x01(\x03R\vtotalChunks\x12'\n" +
	"\x0fcollection_name\x18\x02 \x01(\tR\x0ecollectionName\x12'\n" +
	"\x0fembedding_model\x18\x03 \x01(\tR\x0eembeddingModel2\xfa\x02\n" +
	"\n" +
	"RagService\x12L\n" +
	"\rVectorizeText\x12\x1c.rag.v1.VectorizeTextRequest\x1a\x1d.rag.v1.VectorizeTextResponse\x12X\n" +
	"\x11VectorizeDocument\x12 .rag.v1.VectorizeDocumentRequest\x1a!.rag.v1.VectorizeDocumentResponse\x12L\n" +
	"\rDeleteByDocId\x12\x1c.rag.v1.DeleteByDocIdRequest\x1a\x1d.rag.v1.DeleteByDocIdResponse\x127\n" +
	"\x06Search\x12\x15.rag.v1.SearchRequest\x1a\x16.rag.v1.SearchResponse\x12=\n" +
	"\bGetStats\x12\x17.rag.v1.GetStatsRequest\x1a\x18.rag.v1.GetStatsResponseB)Z'ai_system_oncall/api/proto/rag/v1;ragv1b\x06proto3"

var (
	file_rag_v1_rag_proto_rawDescOnce sync.Once
	file_rag_v1_rag_proto_rawDescData []byte
)

func file_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)))
	})
	return file_rag_v1_rag_proto_rawDescData
}

var file_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rag_v1_rag_proto_goTypes = []any{
	(*VectorizeTextRequest)(nil),      // 0: rag.v1.VectorizeTextRequest
	(*VectorizeTextResponse)(nil),     // 1: rag.v1.VectorizeTextResponse
	(*VectorizeDocumentRequest)(nil),  // 2: rag.v1.VectorizeDocumentRequest
	(*VectorizeDocumentResponse)(nil), // 3: rag.v1.VectorizeDocumentResponse
	(*DeleteByDocIdRequest)(nil),      // 4: rag.v1.DeleteByDocIdRequest
	(*DeleteByDocIdResponse)(nil),     // 5: rag.v1.DeleteByDocIdResponse
	(*SearchRequest)(nil),             // 6: rag.v1.SearchRequest
	(*SearchResponse)(nil),            // 7: rag.v1.SearchResponse
	(*SearchHit)(nil),                 // 8: rag.v1.SearchHit
	(*GetStatsRequest)(nil),           // 9: rag.v1.GetStatsRequest
	(*GetStatsResponse)(nil),          // 10: rag.v1.GetStatsResponse
	nil,                               // 11: rag.v1.SearchHit.MetadataEntry
}
var file_rag_v1_rag_proto_depIdxs = []int32{
	8,  // 0: rag.v1.SearchResponse.hits:type_name -> rag.v1.SearchHit
	11, // 1: rag.v1.SearchHit.metadata:type_name -> rag.v1.SearchHit.MetadataEntry
	0,  // 2: rag.v1.RagService.VectorizeText:input_type -> rag.v1.VectorizeTextRequest
	2,  // 3: rag.v1.RagService.VectorizeDocument:input_type -> rag.v1.VectorizeDocumentRequest
	4,  // 4: rag.v1.RagService.DeleteByDocId:input_type -> rag.v1.DeleteByDocIdRequest
	6,  // 5: rag.v1.RagService.Search:input_type -> rag.v1.SearchRequest
	9,  // 6: rag.v1.RagService.GetStats:input_type -> rag.v1.GetStatsRequest
	1,  // 7: rag.v1.RagService.VectorizeText:output_type -> rag.v1.VectorizeTextResponse
	3,  // 8: rag.v1.RagService.VectorizeDocument:output_type -> rag.v1.VectorizeDocumentResponse
	5,  // 9: rag.v1.RagService.DeleteByDocId:output_type -> rag.v1.DeleteByDocIdResponse
	7,  // 10: rag.v1.RagService.Search:output_type -> rag.v1.SearchResponse
	10, // 11: rag.v1.RagService.GetStats:output_type -> rag.v1.GetStatsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rag_v1_rag_proto_init() }
func file_rag_v1_rag_proto_init() {
	if File_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_rag_v1_rag_proto = out.File
	file_rag_v1_rag_proto_goTypes = nil
	file_rag_v1_rag_proto_depIdxs = nil
}
