// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: rag/v1/rag.proto

package ragv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_VectorizeText_FullMethodName     = "/rag.v1.RagService/VectorizeText"
	RagService_VectorizeDocument_FullMethodName = "/rag.v1.RagService/VectorizeDocument"
	RagService_DeleteByDocId_FullMethodName     = "/rag.v1.RagService/DeleteByDocId"
	RagService_Search_FullMethodName            = "/rag.v1.RagService/Search"
	RagService_GetStats_FullMethodName          = "/rag.v1.RagService/GetStats"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RagService：拆出去独立的 rag-engine 进程（端口 50052）
// - agent-orchestrator 通过 gRPC 调它做检索/向量化
// - backend-api 仍可走 HTTP /api/rag/* 兼容老调用
type RagServiceClient interface {
	VectorizeText(ctx context.Context, in *VectorizeTextRequest, opts ...grpc.CallOption) (*VectorizeTextResponse, error)
	VectorizeDocument(ctx context.Context, in *VectorizeDocumentRequest, opts ...grpc.CallOption) (*VectorizeDocumentResponse, error)
	DeleteByDocId(ctx context.Context, in *DeleteByDocIdRequest, opts ...grpc.CallOption) (*DeleteByDocIdResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) VectorizeText(ctx context.Context, in *VectorizeTextRequest, opts ...grpc.CallOption) (*VectorizeTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorizeTextResponse)
	err := c.cc.Invoke(ctx, RagService_VectorizeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) VectorizeDocument(ctx context.Context, in *VectorizeDocumentRequest, opts ...grpc.CallOption) (*VectorizeDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorizeDocumentResponse)
	err := c.cc.Invoke(ctx, RagService_VectorizeDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DeleteByDocId(ctx context.Context, in *DeleteByDocIdRequest, opts ...grpc.CallOption) (*DeleteByDocIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteByDocIdResponse)
	err := c.cc.Invoke(ctx, RagService_DeleteByDocId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RagService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, RagService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
//
// RagService：拆出去独立的 rag-engine 进程（端口 50052）
// - agent-orchestrator 通过 gRPC 调它做检索/向量化
// - backend-api 仍可走 HTTP /api/rag/* 兼容老调用
type RagServiceServer interface {
	VectorizeText(context.Context, *VectorizeTextRequest) (*VectorizeTextResponse, error)
	VectorizeDocument(context.Context, *VectorizeDocumentRequest) (*VectorizeDocumentResponse, error)
	DeleteByDocId(context.Context, *DeleteByDocIdRequest) (*DeleteByDocIdResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) VectorizeText(context.Context, *VectorizeTextRequest) (*VectorizeTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorizeText not implemented")
}
func (UnimplementedRagServiceServer) VectorizeDocument(context.Context, *VectorizeDocumentRequest) (*VectorizeDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorizeDocument not implemented")
}
func (UnimplementedRagServiceServer) DeleteByDocId(context.Context, *DeleteByDocIdRequest) (*DeleteByDocIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByDocId not implemented")
}
func (UnimplementedRagServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRagServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call panics, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_VectorizeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorizeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).VectorizeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_VectorizeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).VectorizeText(ctx, req.(*VectorizeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_VectorizeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorizeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).VectorizeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_VectorizeDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).VectorizeDocument(ctx, req.(*VectorizeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DeleteByDocId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByDocIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DeleteByDocId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DeleteByDocId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DeleteByDocId(ctx, req.(*DeleteByDocIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.v1.RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VectorizeText",
			Handler:    _RagService_VectorizeText_Handler,
		},
		{
			MethodName: "VectorizeDocument",
			Handler:    _RagService_VectorizeDocument_Handler,
		},
		{
			MethodName: "DeleteByDocId",
			Handler:    _RagService_DeleteByDocId_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RagService_Search_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _RagService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag/v1/rag.proto",
}
