// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunAgentRequest 启动 agent 分析的请求（Worker -> Agent）
type RunAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IssueId       int64                  `protobuf:"varint,2,opt,name=issue_id,json=issueId,proto3" json:"issue_id,omitempty"`
	IssueNo       string                 `protobuf:"bytes,3,opt,name=issue_no,json=issueNo,proto3" json:"issue_no,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LogExcerpt    string                 `protobuf:"bytes,7,opt,name=log_excerpt,json=logExcerpt,proto3" json:"log_excerpt,omitempty"`
	Environment   string                 `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	ProjectId     uint64                 `protobuf:"varint,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,10,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ServiceName   string                 `protobuf:"bytes,11,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ImpactScope   string                 `protobuf:"bytes,12,opt,name=impact_scope,json=impactScope,proto3" json:"impact_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentRequest) Reset() {
	*x = RunAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentRequest) ProtoMessage() {}

func (x *RunAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentRequest.ProtoReflect.Descriptor instead.
func (*RunAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RunAgentRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RunAgentRequest) GetIssueId() int64 {
	if x != nil {
		return x.IssueId
	}
	return 0
}

func (x *RunAgentRequest) GetIssueNo() string {
	if x != nil {
		return x.IssueNo
	}
	return ""
}

func (x *RunAgentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RunAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RunAgentRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RunAgentRequest) GetLogExcerpt() string {
	if x != nil {
		return x.LogExcerpt
	}
	return ""
}

func (x *RunAgentRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RunAgentRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *RunAgentRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *RunAgentRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RunAgentRequest) GetImpactScope() string {
	if x != nil {
		return x.ImpactScope
	}
	return ""
}

// RunAgentResponse 流上的事件
type RunAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunAgentResponse_Progress
	//	*RunAgentResponse_Result
	//	*RunAgentResponse_Error
	Event         isRunAgentResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentResponse) Reset() {
	*x = RunAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentResponse) ProtoMessage() {}

func (x *RunAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentResponse.ProtoReflect.Descriptor instead.
func (*RunAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RunAgentResponse) GetEvent() isRunAgentResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunAgentResponse) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Event.(*RunAgentResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *RunAgentResponse) GetResult() *AgentResult {
	if x != nil {
		if x, ok := x.Event.(*RunAgentResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *RunAgentResponse) GetError() *ErrorInfo {
	if x != nil {
		if x, ok := x.Event.(*RunAgentResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRunAgentResponse_Event interface {
	isRunAgentResponse_Event()
}

type RunAgentResponse_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,1,opt,name=progress,proto3,oneof"` // 进度更新（多次）
}

type RunAgentResponse_Result struct {
	Result *AgentResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"` // 最终结果（一次）
}

type RunAgentResponse_Error struct {
	Error *ErrorInfo `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // 失败信息（一次）
}

func (*RunAgentResponse_Progress) isRunAgentResponse_Event() {}

func (*RunAgentResponse_Result) isRunAgentResponse_Event() {}

func (*RunAgentResponse_Error) isRunAgentResponse_Event() {}

type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	StepLabel     string                 `protobuf:"bytes,2,opt,name=step_label,json=stepLabel,proto3" json:"step_label,omitempty"` // "1/8", "加载上下文"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                      // 详细说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressUpdate) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ProgressUpdate) GetStepLabel() string {
	if x != nil {
		return x.StepLabel
	}
	return ""
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AgentResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Summary         string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	IssueType       string                 `protobuf:"bytes,2,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	RelatedServices []string               `protobuf:"bytes,3,rep,name=related_services,json=relatedServices,proto3" json:"related_services,omitempty"`
	SuspectedCause  string                 `protobuf:"bytes,4,opt,name=suspected_cause,json=suspectedCause,proto3" json:"suspected_cause,omitempty"`
	Evidence        []*EvidenceItem        `protobuf:"bytes,5,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Suggestions     []string               `protobuf:"bytes,6,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	MissingInfo     []string               `protobuf:"bytes,7,rep,name=missing_info,json=missingInfo,proto3" json:"missing_info,omitempty"`
	NextSteps       []string               `protobuf:"bytes,8,rep,name=next_steps,json=nextSteps,proto3" json:"next_steps,omitempty"`
	Confidence      float64                `protobuf:"fixed64,9,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ToolCalls       []*ToolCallRecord      `protobuf:"bytes,10,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentResult) Reset() {
	*x = AgentResult{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResult) ProtoMessage() {}

func (x *AgentResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResult.ProtoReflect.Descriptor instead.
func (*AgentResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AgentResult) GetIssueType() string {
	if x != nil {
		return x.IssueType
	}
	return ""
}

func (x *AgentResult) GetRelatedServices() []string {
	if x != nil {
		return x.RelatedServices
	}
	return nil
}

func (x *AgentResult) GetSuspectedCause() string {
	if x != nil {
		return x.SuspectedCause
	}
	return ""
}

func (x *AgentResult) GetEvidence() []*EvidenceItem {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *AgentResult) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *AgentResult) GetMissingInfo() []string {
	if x != nil {
		return x.MissingInfo
	}
	return nil
}

func (x *AgentResult) GetNextSteps() []string {
	if x != nil {
		return x.NextSteps
	}
	return nil
}

func (x *AgentResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AgentResult) GetToolCalls() []*ToolCallRecord {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type EvidenceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Relevance     string                 `protobuf:"bytes,3,opt,name=relevance,proto3" json:"relevance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceItem) Reset() {
	*x = EvidenceItem{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceItem) ProtoMessage() {}

func (x *EvidenceItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceItem.ProtoReflect.Descriptor instead.
func (*EvidenceItem) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *EvidenceItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EvidenceItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EvidenceItem) GetRelevance() string {
	if x != nil {
		return x.Relevance
	}
	return ""
}

type ToolCallRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         string                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Thought       string                 `protobuf:"bytes,5,opt,name=thought,proto3" json:"thought,omitempty"`
	ExecutedAt    string                 `protobuf:"bytes,6,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	DurationMs    int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallRecord) Reset() {
	*x = ToolCallRecord{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallRecord) ProtoMessage() {}

func (x *ToolCallRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallRecord.ProtoReflect.Descriptor instead.
func (*ToolCallRecord) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallRecord) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ToolCallRecord) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallRecord) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *ToolCallRecord) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolCallRecord) GetThought() string {
	if x != nil {
		return x.Thought
	}
	return ""
}

func (x *ToolCallRecord) GetExecutedAt() string {
	if x != nil {
		return x.ExecutedAt
	}
	return ""
}

func (x *ToolCallRecord) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"\x88\x03\n" +
	"\x0fRunAgentRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x19\n" +
	"\bissue_id\x18\x02 \x01(\x03R\aissueId\x12\x19\n" +
	"\bissue_no\x18\x03 \x01(\tR\aissueNo\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vlog_excerpt\x18\a \x01(\tR\n" +
	"logExcerpt\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\x04R\tprojectId\x12!\n" +
	"\fproject_name\x18\n" +
	" \x01(\tR\vprojectName\x12!\n" +
	"\fservice_name\x18\v \x01(\tR\vserviceName\x12!\n" +
	"\fimpact_scope\x18\f \x01(\tR\vimpactScope\"\xb1\x01\n" +
	"\x10RunAgentResponse\x126\n" +
	"\bprogress\x18\x01 \x01(\v2\x18.agent.v1.ProgressUpdateH\x00R\bprogress\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x15.agent.v1.AgentResultH\x00R\x06result\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x13.agent.v1.ErrorInfoH\x00R\x05errorB\a\n" +
	"\x05event\"]\n" +
	"\x0eProgressUpdate\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x1d\n" +
	"\n" +
	"step_label\x18\x02 \x01(\tR\tstepLabel\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8b\x03\n" +
	"\vAgentResult\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"issue_type\x18\x02 \x01(\tR\tissueType\x12)\n" +
	"\x10related_services\x18\x03 \x03(\tR\x0frelatedServices\x12'\n" +
	"\x0fsuspected_cause\x18\x04 \x01(\tR\x0esuspectedCause\x122\n" +
	"\bevidence\x18\x05 \x03(\v2\x16.agent.v1.EvidenceItemR\bevidence\x12 \n" +
	"\vsuggestions\x18\x06 \x03(\tR\vsuggestions\x12!\n" +
	"\fmissing_info\x18\a \x03(\tR\vmissingInfo\x12\x1d\n" +
	"\n" +
	"next_steps\x18\b \x03(\tR\tnextSteps\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\x01R\n" +
	"confidence\x127\n" +
	"\n" +
	"tool_calls\x18\n" +
	" \x03(\v2\x18.agent.v1.ToolCallRecordR\ttoolCalls\"^\n" +
	"\fEvidenceItem\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\trelevance\x18\x03 \x01(\tR\trelevance\"\xcb\x01\n" +
	"\x0eToolCallRecord\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x18\n" +
	"\athought\x18\x05 \x01(\tR\athought\x12\x1f\n" +
	"\vexecuted_at\x18\x06 \x01(\tR\n" +
	"executedAt\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\"9\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2S\n" +
	"\fAgentService\x12C\n" +
	"\bRunAgent\x12\x19.agent.v1.RunAgentRequest\x1a\x1a.agent.v1.RunAgentResponse0\x01B-Z+ai_system_oncall/api/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_v1_agent_proto_goTypes = []any{
	(*RunAgentRequest)(nil),  // 0: agent.v1.RunAgentRequest
	(*RunAgentResponse)(nil), // 1: agent.v1.RunAgentResponse
	(*ProgressUpdate)(nil),   // 2: agent.v1.ProgressUpdate
	(*AgentResult)(nil),      // 3: agent.v1.AgentResult
	(*EvidenceItem)(nil),     // 4: agent.v1.EvidenceItem
	(*ToolCallRecord)(nil),   // 5: agent.v1.ToolCallRecord
	(*ErrorInfo)(nil),        // 6: agent.v1.ErrorInfo
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	2, // 0: agent.v1.RunAgentResponse.progress:type_name -> agent.v1.ProgressUpdate
	3, // 1: agent.v1.RunAgentResponse.result:type_name -> agent.v1.AgentResult
	6, // 2: agent.v1.RunAgentResponse.error:type_name -> agent.v1.ErrorInfo
	4, // 3: agent.v1.AgentResult.evidence:type_name -> agent.v1.EvidenceItem
	5, // 4: agent.v1.AgentResult.tool_calls:type_name -> agent.v1.ToolCallRecord
	0, // 5: agent.v1.AgentService.RunAgent:input_type -> agent.v1.RunAgentRequest
	1, // 6: agent.v1.AgentService.RunAgent:output_type -> agent.v1.RunAgentResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*RunAgentResponse_Progress)(nil),
		(*RunAgentResponse_Result)(nil),
		(*RunAgentResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
